#!/usr/bin/perl

# Runs the given problem, writing the parameters/commit info
# and the solution to the sol/ directory

use strict;

my @args = ('./score', '+RTS', '-K32000000', '-RTS');
my @outputs = ();
my $verbose = 0;

while ($_ = shift) {
  if ($_ eq '--verbose') { $verbose = 1; next; }
  if (-e $_) { push @outputs, $_; next; }
  # error?
}
push @outputs, "/dev/stdin" unless @outputs;

foreach (@outputs) {
  push @args, "-s", $_;
}

# problems
opendir PROBS, "problems";
while ($_ = readdir PROBS) {
  if (/\.json$/) {
    push @args, "-f", "problems/$_";
  }
}
closedir PROBS;

# phrases of power
open POWER, "words";
while ($_ = <POWER>) {
  chomp $_;
  s/#.*//;
  next unless /\S/;
  push @args, "-p", $_;
}
close POWER;

push @args, '--verbose' if $verbose;

system "make", "score";
system @args;
