#!/usr/bin/perl

# Runs the given problem, writing the parameters/commit info
# and the solution to the sol/ directory

my @args = ('./score');
my @outputs = ();
my $verbose = 1;

while ($_ = shift) {
  if ($_ eq '--quiet') { $verbose = 0; next; }
  if (-e $_) { push @outputs, $_; next; }
  # error?
}
push @outputs, "/dev/stdin" unless @outputs;

foreach (@outputs) {
  push @args, "-s", $_;
}

# problems
opendir PROBS, "problems";
while ($_ = readdir PROBS) {
  if (/\.json$/) {
    push @args, "-f", "problems/$_";
  }
}
closedir PROBS;

# phrases of power
if ($use_power) {
  open POWER, "words";
  while ($_ = <POWER>) {
    chomp $_;
    s/#.*//;
    next unless /\S/;
    push @args, "-p", $_;
  }
  close POWER;
}

push @args, '--verbose' if $verbose;

system "make", "score";
system @args;
