#!/usr/bin/perl

use strict;

my @probs = (15, 20);
my @query = ();
while (@ARGV) {
  $_ = shift;
  my $num = shift @probs or die "too many";
  next unless $_;
  my $code = $_;
  my $len = length($code) - 2;
  $code =~ s/(.).*(.)/$1$len$2/;
  my $json = '{"problemId":NUM,"seed":0,"tag":"____NUM:CODE____","solution":"SOL"}';
  my $sol = 'la' . $_ . 'lalalalalalalalalalalalalalalalalala';
  $json =~ s/NUM/$num/g;
  $json =~ s/CODE/$code/g;
  $json =~ s/SOL/$sol/g;
  push @query, $json;

  open WORD, ">/tmp/word";
  print WORD "[$json]\n";
  close WORD;
  system "./score --split -f problems/problem_$num.json -s /tmp/word";
}

$" = ',';
my @cmd = ('curl', '--user', ':xpjucYvS2nEAjnlhHLNAjO32W8TS5s0VhBCPQUOoWvU=',
  '-X', 'POST', '-H', 'Content-Type: application/json', '-d', "[@query]",
  'https://davar.icfpcontest.org/teams/232/solutions');
$" = ' ';
print "@cmd\n";
system @cmd;
