#!/usr/bin/perl

use strict;

my @probs = ('12:0', '12:24762', '12:24103', '12:12700', '12:5864', '12:1155', '12:24803', '12:29992', '12:18660', '12:19102', '15:0', '20:0');
my @query = ();
while (@ARGV) {
  $_ = shift;
  my $prob = $probs[0] or die "too many";
  $prob =~ /(\d+):(\d+)/ or die 'bad form';
  my $num = $1;
  my $seed = $2;
  my $code = $_;
  my $len = length($code) - 2;
  $code =~ s/(.).*(.)/$1$len$2/;
  my $json = '{"problemId":NUM,"seed":SEED,"tag":"_POWER_","solution":"SOL"}';
  my $sol = 'la' . $_ . 'lalalalalalalalalalalalalalalalalala';
  $json =~ s/NUM/$num/g;
  $json =~ s/SEED/$seed/g;
  $json =~ s/CODE/$code/g;
  $json =~ s/SOL/$sol/g;

  open WORD, ">/tmp/word";
  print WORD "[$json]\n";
  close WORD;
  my $result = `./score --split -f problems/problem_$num.json -s /tmp/word`;
  print $result;
  if ($result =~ /repeat/ or ($result =~ /(\d+) unused/ and $1 > 36)) {
    print "Skipping $_\n";
    next;
  }
  shift @probs;
  push @query, $json;
}

die "nothing to do" unless @query;

$" = ',';
my @cmd = ('curl', '--user', ':xpjucYvS2nEAjnlhHLNAjO32W8TS5s0VhBCPQUOoWvU=',
  '-X', 'POST', '-H', 'Content-Type: application/json', '-d', "[@query]",
  'https://davar.icfpcontest.org/teams/232/solutions');
$" = ' ';
print "@cmd\n";
system @cmd;
